categories:
  - title: '🚀 Added'
    labels:
      - 'feature'
      - 'feat'
  - title: '🐛 Fixed'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Changed'
    label: 'refactor'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  default: minor
template: |
  ## Changes

  $CHANGES
