style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/ryan-sf/package_releases
options:
  commits:
    filters:
      Type:
        - feat
        - fix
        - remove
        - deprecate
        - refactor
        - docs
  commit_groups:
    title_maps:
      feat: Added
      fix: Fixed
      remove: Removed
      deprecate: Deprecated
      refactor: Changed
      docs: Documented
  header:
    pattern: "^(\\w*)\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
