name: Auto Release Drafter
on:
  pull_request:
    branches:
      - master
    types: [closed]
    
jobs:
  release:
    name: Create release
    runs-on: macos-latest
    if: github.event.pull_request.merged == true
    env:
      breaking: contains(github.event.pull_request.labels.*.name, 'breaking')
    steps:
        - name: Checkout
          uses: actions/checkout@v2
            
        - name: Install Flutter
          uses: subosito/flutter-action@v1.4.0

        - name: Install project dependencies
          run: |
            flutter pub global activate cider
            
        - name: Minor version
          if: ${{!breaking}}
          run: |
            flutter pub global run cider bump minor
            VERSION=$(flutter pub global run cider version) 
            echo "Outputting new minor version: ${VERSION}"
            echo "::set-output name=version::${VERSION}"
            
        - name: Major version
          if: ${{breaking}}
          run: |
            flutter pub global run cider bump major
            VERSION=$(flutter pub global run cider version) 
            echo "Outputting new major version: ${VERSION}"
            echo "::set-output name=version::${VERSION}"
            
        - name: Commit version
          uses: stefanzweifel/git-auto-commit-action@v4 
          
        - name: Get tags
          run: |
            git fetch --all --tags 
            git tag "v${{steps.version.outputs.version}}"
            git push && git push --tags
              
        - name: Draft release
          uses: release-drafter/release-drafter@v5
          with:
            name: v${{steps.version.outputs.version}}
            config-name: release-drafter.yml
            version: v${{steps.version.outputs.version}}
            tag: v${{steps.version.outputs.version}}
            publish: true
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
